// Words the workshop screens (packages E1-E6) show that no stage file carries: output labels, button
// labels, failure lines, units. Dial names, effects and reasons come from the stage YAML via the kit.
// `{name}` placeholders are filled by `fill()` from ../strings.

export const WS = {
  frame: {
    outputs: "Outputs",
    history: "What you tried",
    needs: "needs {name}",
    notEnough: "Not enough {name}: {have} of {need}.",
    running: "{what}: day {day} of {days}.",
    none: "—",
    pendingH: "found by the test campaign",
  },
  furnace: {
    charge: "This campaign",
    chargeKinds: { copper: "Copper", iron_bloom: "Iron bloom", iron_blast: "Blast furnace" } as Record<string, string>,
    temperature: "Hottest the charge gets",
    required: "Needs",
    ore: "Ore charged",
    fuel: "Fuel burned",
    lime: "Lime charged",
    metal: "Metal out",
    blast: "Blast",
    cokeRate: "Fuel per ton of iron",
    ironQuality: "Iron quality (0-3)",
    campaigns: "Campaigns run",
    run: "Run a campaign ({days} days)",
    runTitle: "Run",
    converter: "Converter heat",
    carbon: "Carbon left",
    steelQuality: "Steel quality (0-3)",
    blow: "Blow a heat",
    pig: "Pig iron charged",
    steel: "Steel out",
    ok: "The metal ran.",
    calm: "Calm season on the ridge: the wind site gives {pct}% of its output.",
    failures: {
      too_cold: "The charge never got hot enough: the ore sat in the fire and nothing ran. Fuel burned anyway.",
      cast_lumps: "Too much charcoal: the iron took up carbon and came out as brittle cast lumps, not a bloom.",
      frozen_short_stack: "The stack is too short for iron to take up carbon and melt: the slag froze.",
      frozen_weak_blast: "Not enough blast for this stack: the furnace chilled and the slag froze.",
      under_blown: "Stopped too early: carbon left in, the steel is hard and brittle.",
      over_blown: "Blown too long: the metal took up oxygen and is weak. Manganese would recover it.",
    } as Record<string, string>,
    coldShort: "Phosphorus stayed in (acid lining): the steel is brittle when cold.",
    hotShort: "Sulfur stayed in (no manganese): the steel cracks at forging heat.",
    result: "{metal} {unit} of {what}",
    failed: "failed",
  },
  engine: {
    design: "This design",
    kind: { savery: "Savery pump", newcomen: "Atmospheric engine", watt: "Condensing engine", high_pressure: "High-pressure engine" } as Record<string, string>,
    mover: { turbine: "Steam turbine", water_turbine: "Water turbine" } as Record<string, string>,
    shaft: "Shaft power",
    water: "Water lifted",
    coal: "Coal",
    coalPerKwh: "Coal per kWh",
    iron: "Iron to build",
    margin: "Safety margin",
    stress: "Hoop stress (P r / t)",
    safe: "Safe for good",
    bursts: "Bursts {years} years after first firing",
    burstsOn: "Bursts in year {year}, day {day}",
    suction: "Suction alone lifts {m} m; the rest needs steam pressure the soldered boiler can't hold safely.",
    dynamo: "Generator output",
    limited: { none: "", shaft_power: "limited by the shaft's power", shaft_speed: "limited by the shaft's speed", bearing_speed: "limited by the bearings: the shaft can't turn faster", machine_size: "one machine's most", magnets: "permanent magnets cap it" } as Record<string, string>,
    needsRotative: "A beam pump can't turn a generator: it needs rotative output.",
    loss: "Line loss",
    delivered: "Delivered to the colony",
    efficiency: "Coal to electricity",
    build: "Build it ({days} days)",
    building: "Building",
    running: "Running now",
    none: "No engine built from this workshop yet.",
    burst: "The boiler burst: the engine is lost.",
    built: "Built and running.",
    replaced: "replaces the running engine when it's done",
    lowIron: "Iron quality is low: plate strength falls by a third.",
  },
  shop: {
    setup: "This setup",
    tolerance: "Tolerance the shop holds",
    bearings: "Bearing quality (0-3)",
    hours: "Shop hours a day",
    machinists: "Machinists",
    queueDays: "The queue takes",
    days: "{n} days",
    wasted: "Hours lost to rejects",
    balance: "Shop hours spare a day",
    retool: "Retool the shop ({days} days)",
    retooling: "Retooling",
    current: "The shop now",
    queue: "Parts queue",
    queueHint: "First in the queue is made first. A part tighter than the shop can hold is remade until one fits.",
    empty: "Nothing queued yet: parts join as engines, rails and machines are built.",
    part: "{hours} h, needs {tol} mm",
    reject: "{pct}% remade",
    late: "late: after a year",
    finish: "done by day {n}",
    up: "↑",
    down: "↓",
    upLabel: "Move {name} up",
    downLabel: "Move {name} down",
    noMachinists: "No machinists trained yet: train some (idle people learn the trade you pick).",
    adopted: "{tol} mm, bearing quality {bq}.",
  },
  liquefier: {
    design: "This plant",
    method: { cascade: "Cascade", throttle_regenerative: "Linde", expansion_engine: "Claude" } as Record<string, string>,
    compressor: "Compressor",
    liters: "Liquid a day",
    kg: "Liquid a day (kg)",
    oxygen: "Oxygen in it a day",
    kwh: "Electricity per kg",
    purity: "Oxygen purity",
    firstDrop: "First drop after",
    asymptote: "Coldest it can get",
    never: "never: the cold end stalls above -190 °C",
    days: "{n} days",
    start: "Start the plant",
    restart: "Restart with this design",
    stop: "Stop the plant",
    cooling: "Cooling down",
    temp: "Cold end now",
    running: "Running: {kg} kg of liquid a day, {o2} kg oxygen",
    stalled: "The cold end stalled at {t} °C: longer exchanger, more pressure, or an expansion engine.",
    firstDropAt: "First drop: {kg} kg of liquid a day at {pur}% oxygen.",
    stopped: "Stopped.",
    chart: "Cold-end temperature, °C, by day",
  },
  rocketEngine: {
    design: "This engine",
    propellants: { ethanol_lox: "alcohol and LOX", kerosene_lox: "kerosene and LOX", hypergolic: "hypergolics" } as Record<string, string>,
    burning: "Burns {name}",
    thrust: "Thrust at sea level",
    thrustVac: "Thrust in vacuum",
    ispSl: "Isp at sea level",
    ispVac: "Isp in vacuum",
    burn: "Chamber lasts",
    holds: "indefinitely",
    pc: "Chamber pressure",
    lox: "LOX per firing",
    flaws: "Flaws found",
    feedLimited: "The feed can't reach this chamber pressure: capped at {pc} bar.",
    rough: "Rough burning: combustion instability is likely at this pressure with this injector.",
    oxRich: "Oxidizer-rich: the hot gas attacks the wall.",
    separation: "Over-expanded at sea level: the flow leaves the nozzle wall (side loads).",
    queueIt: "Queue it for the stand",
    queue: "Stand queue",
    queueEmpty: "Nothing waiting for the stand.",
    firing: "On the stand",
    waitingLox: "Waiting for LOX: {have} of {need} kg.",
    first: "Fire first",
    drop: "Remove",
    best: "Best firing",
    bestLine: "{s} s at {kn} kN",
    none: "No firing yet.",
    fired: "{s} s at {kn} kN, Isp {isp} s.",
    burnedThrough: "Burned through at {s} s; {kn} kN while it lasted.",
    trace: "Chamber pressure, bar, by second",
    standDays: "Stand days queued",
  },
  rocket: {
    vehicle: "Vehicle design",
    payload: "Payload: a {t} t capsule with one pilot.",
    stage: "Stage {n}",
    lander: "Last stage",
    dry: "Dry (t)",
    dv: "Δv (km/s)",
    liftoff: "Mass at liftoff",
    total: "Total Δv",
    budget: "Mission budget",
    margin: "Margin",
    flawsExpected: "Flaws expected",
    marks: { orbit: "Orbit", moon: "Toward the Moon", landed: "Landed" },
    enough: "Enough on paper, with {spare} km/s spare.",
    short: "Short by {short} km/s.",
    reach: {
      short_of_orbit: "This never reaches orbit.",
      orbit: "This reaches orbit but not the Moon.",
      toward_moon: "The capsule reaches the Moon and hits it too fast.",
      landed: "",
    } as Record<string, string>,
    budgetNote: "The budget includes gravity and drag losses on the way up, and what midcourse correction and crew safety spend.",
    single: "Even with no payload at all, one stage like this tops out at {dv} km/s: orbit needs {orbit}. Staging throws the empty tanks away.",
    adopt: "Adopt this design",
    adopted: "The vehicle",
    none: "No design adopted yet: the test campaign needs one.",
    adoptedLine: "{dv} km/s, margin {m} km/s, {t} t at liftoff.",
  },
} as const;
