// The UI's small strings file (docs/work-packages.md, Conventions: "Everything the player reads comes
// from the YAML or a small strings file"). Words that belong to the frame, not to any stage: button
// labels, panel headings, pause reasons, units. Stage text (node names, problems, notebook entries,
// pressure names, job names and lines, the opening problem) comes from tech-tree/ via src/content.
//
// `{name}` placeholders are filled by `fill()`.

export const STRINGS = {
  title: "Bootstrap",
  tree: {
    inc: "+",
    dec: "−",
    expand: "▸",
    collapse: "▾",
    pin: "pin",
    unpin: "pinned",
    edit: "Double-click to type a number for {name}",
  },
  header: {
    stage: "Stage {n}, {name}",
    date: "Year {year}, day {day}",
    speed: "Speed",
    speedX: "{n}×",
    energyUnit: "watts per person",
    notebook: "Notebook",
    map: "Tech map",
    back: "Back to the colony",
    theme: "Light / dark",
    reset: "New run",
    resetConfirm: "Start a new run? This one is erased.",
  },
  meter: {
    you: "You",
    w: "{n} W",
    kw: "{n} kW",
  },
  goal: {
    line: "{name}: {unmet}.",
    now: "{text} (now {n})",
    route: "{name}: finish one route: {list}.",
    routeJoiner: " or ",
    reached: "Gate reached: {name}.",
    joiner: ", ",
  },
  stores: {
    heading: "Stores",
    perDay: "{sign}{n}/day",
    plus: "+",
    minus: "−",
    demand: "needs {n}/day",
    claimed: "{n} waiting for projects",
    empty: "Nothing in store yet.",
  },
  tools: {
    line: "{tools} tools for {users} people who need them.",
    bare: "{n} working bare-handed.",
  },
  people: {
    heading: "People",
    idle: "Idle",
    training: "Idle people train as",
    trainingNone: "nothing in particular",
    trainingExplain: "Nobody idle is wasted: they learn the trade you pick. Every {days} idle person-days make one trained worker ({perDay} a day with {idle} idle now).",
    trainingCounts: "Trained so far: {list}.",
    trainingCount: "{n} {label}",
    trainingNext: "Next {label}: {pct}% of the way.",
    trainingMatters: "{label} matter for: {list}.",
    short: "short of {what}",
    pullCapped: "stopped: nobody needs more",
    target: "target {n}/day",
    pull: "fills demand",
    shortfall: "{n} short",
    priority: "priority {n}",
  },
  projects: {
    heading: "Projects",
    nothing: "Nothing to build yet. Keep working; new problems will surface.",
    materials: "Materials: {list}.",
    labor: "Labor: {n} person-days.",
    effect: "Effect: {list}.",
    start: "Start building",
    progress: "{done} of {total} person-days",
    noBuilders: "Nobody is assigned to build.",
    why: "Why this works",
    missing: "Short of {list}.",
    suggested: "Answers a red bar",
    milestone: "At {pct}%: {text}",
    chooseOne: "Choose one",
    chooseOneNote: "Starting one closes the other for good.",
    choose: "Choose this",
    choseOver: "Chosen over {list}.",
    or: " or ",
    workshopsHeading: "Workshops",
  },
  pressures: {
    heading: "Pressures",
    red: "Red: {effect}",
    warn: "Heading for red: {effect}",
    answers: "Answers: {list}",
    hintReady: "{name} (ready to start)",
    hintBuilding: "{name} (being built)",
    hintDone: "{name} (done)",
    hintLater: "{name} (later, after {after})",
    hintSoon: "{name} (coming)",
    fixes: "What fixes this: {list}",
  },
  log: {
    heading: "Log",
    stamp: "Year {year}, day {day}.",
    started: "Started: {name}.",
    node_complete: "Finished: {name}.",
    node_revealed: "A new problem needs solving: {name}.",
    milestone: "Milestone: {name}.",
    pressure_red: "{name} is red.",
    workshop_open: "Workshop open: {name}.",
    gate: "Stage {n} complete.",
    stuck: "Nothing to build: see Projects for what's blocking.",
  },
  pause: {
    node_revealed: "New problem: {name}",
    node_complete: "Finished: {name}",
    milestone: "Milestone: {name}",
    pressure_red: "{name} is red",
    workshop_open: "Workshop open: {name}",
    gate: "Stage {n} gate reached",
    stuck: "Nothing to build: see Projects for what's blocking",
    join: " · ",
    backTo: "Back to {n}×",
    ok: "Got it",
    newHere: "New",
  },
  stuck: {
    heading: "Nothing to build right now",
    waiting: "{name} is waiting on: {list}.",
    more: "{n} more {name}",
    cond: "{name} {op} {value}",
    has: "{name} includes {member}",
    not: "not {cond}",
    and: " and ",
    or: " or ",
    ops: { ">": "above", "<": "below", ">=": "at least", "<=": "at most", "==": "equal to", "!=": "not" },
    cantMake: "This build can't reach this stage's gate: nothing makes or measures {list}. The stage's content isn't finished yet, and no amount of waiting will change that.",
    hint: "Start a project, or put people on the jobs that make what a project lacks.",
  },
  map: {
    heading: "Tech map",
    intro: "Six stages from bare hands to the Moon. Each ends at a gate; each gate needs more energy per person. Pick a stage to see its projects and what leads to what.",
    stage: "Stage {n}",
    gateLine: "Gate: {name}",
    watts: "{n} W a person",
    count: "{done} of {total} done",
    moon: "The Moon",
    here: "You are here",
    beat: "Step {n}",
    legend: "Done · Being built · Ready to start · Not taken · Ahead",
    either: "either/or",
    done: "done",
    building: "being built",
    ready: "ready to start",
    closed: "not taken",
    ahead: "ahead",
  },
  notebook: {
    heading: "Notebook",
    empty: "Entries fill in as projects are completed.",
    stage: "Stage {n}, {name}",
  },
  gate: {
    banner: "Stage {n} complete: {name}",
    time: "Time: year {year}, day {day}.",
  },
  draft: {
    hook: "The draft screen isn't on this build yet. Departing with the default draft.",
    depart: "Depart",
    title: "The draft",
    rosterHeading: "Who goes",
    pagesHeading: "What they carry",
    ofFull: "of {full}",
    peopleLine: "{used} of {total} people",
    pagesLine: "{used} of {budget} pages",
    weakest: "Weakest area: {name}",
    changes: "Changes: {list}",
  },
} as const;

/** Fill `{key}` placeholders. Unknown keys are left as they are. */
export function fill(template: string, values: Readonly<Record<string, string | number>>): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in values ? String(values[k]) : m));
}
