// The typed tech tree. The only module other packages import from src/content.
// tree.json is generated by scripts/build-content.mjs (npm run content; run before test,
// typecheck, dev and build).

import raw from "./tree.json";
import type { Tree } from "./types";

export const tree: Tree = raw as unknown as Tree;

export * from "./types";
export { parseExpr, printExpr, normalize, exprRefs, exprLeaves, ExprParseError, CMP_OPS } from "./expr";
export * from "./evaluate";
export * from "./nodes";
